# Change these first
owner:  NotExpectedYet # Your GitHub username
repo: service-monitoring # Your GitHub repository name

# Add your sites here
sites:
  - name: OctoFarm
    url: https://octofarm.net

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
   baseUrl: /service-monitoring # where "repo" is your repository name
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: NotExpectedYet Uptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: "Welcome, check out NotExpectedYet services current uptime below."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
